### ISSUE TITLE
Request for the removal of Tailwind css 

### ISSUE THREAD

**Issue by umeh-promise** [laststance/vite-rtk-query#427]
Thank you for taking the time to provide a template for using Redux Toolkit with Vite in a React application. I appreciate your effort in creating this solution.

In my case, I do not require Tailwind CSS in the template. I feel that Tailwind CSS may not be necessary for certain projects that I am working on.. However, I think the solution would be more suitable for my needs if we remove this addition and focus solely on the integration of Redux Toolkit with Vite and Typescript in a React application.

Thank you.

**Comment by ryota-murakami** [comment]
@umeh-promise Thank you for your feedback!
I know that feeling, I think less unnecessary or opinionated tools are good for a pure RTK React template.

TailwindCSS had enormous popularity and dominant share when I started this project., that why TailwindCSS is exiting.

Could you please wait to make a final decision on this?
I'd like to collect community votes to see know how many people want TailwindCSS.

Until then, I'll add `npm run remove:tailwind` script for who don't need TailwindCSS in https://github.com/laststance/vite-rtk-query/pull/428.

**Comment by umeh-promise** [comment]
Thank you for considering my feedback and for adding the option to remove Tailwind CSS with the "npm run remove:tailwind" script. I appreciate your willingness to collect community votes on the matter. I am open to waiting until the community has had the chance to provide their input on whether or not they want Tailwind CSS included in the template. Thank you for being responsive to feedback and for making changes to accommodate different preferences.

**Comment by ryota-murakami** [comment]
@umeh-promise I added `npm run remove:tailwind` script now. https://github.com/laststance/vite-rtk-query/pull/428
Can you execute the command without error?

**Comment by umeh-promise** [comment]
Thank you for adding the 'npm run remove:tailwind' command to the template. I was able to run it without any errors and it worked as intended. Your contribution is greatly appreciated and adds significant value to the template. Thank you for being responsive to feedback and for your ongoing efforts to improve the template for the community.

**Comment by ryota-murakami** [comment]
@umeh-promise I'm glad to hear that from you. Thank you!

**Comment by kirkbross** [comment]
I get `'.' is not recognized as an internal or external command, operable program or batch file.` when I try to run remove:tailwind. Both with npm and yarn.

**Comment by ryota-murakami** [comment]
@kirkbross I've just fix commit.
Could you retry form `npx degit laststance/vite-rtk-query myapp`?

**Comment by kirkbross** [comment]
@ryota-murakami That worked. 

I tried it with an `npm install` and `npm run remove:tailwind` and also with `yarn install` / `yarn run remove:tailwind` -- both worked.

**Comment by ryota-murakami** [comment]
@kirkbross I'm glad to hear that.

> also with yarn install / yarn run remove:tailwind

It because using npm in `remove_tailwind.js` script that doesn't matter kicking npm script by what kind of package manager.
https://github.com/laststance/vite-rtk-query/blob/main/scripts/remove_tailwind.js#L48
